apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image:  rafayzia3690/go-app:1.0.0
        env:
        - name: DB_HOST
          value: postgres-db-service
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: "1234567890"
        - name: DB_NAME
          value: postgres
        ports:
        - containerPort: 8080
