apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  DB_HOST: postgres-database
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: "1234567890"
  DB_NAME: postgres



